"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file at project root (if present)
load_dotenv(BASE_DIR / ".env")


def _env_bool(key: str, default: bool = False) -> bool:
    val = os.environ.get(key)
    if val is None:
        return default
    return str(val).strip().lower() in ("1", "true", "t", "yes", "y", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-u^i4qrjlyd&+zgx%c%=a)#$8zhxzh8@sjign#17y8ll4$-%fx1"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "t")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
ALLOWED_HOSTS += ["fikrly.uz", "www.fikrly.uz"]

CSRF_TRUSTED_ORIGINS = ["https://fikrly.uz", "https://www.fikrly.uz"]

if DEBUG:
    # Allow Cloudflare Quick Tunnel random subdomains and local binds during development
    ALLOWED_HOSTS = list({*ALLOWED_HOSTS, ".trycloudflare.com", "0.0.0.0"})
    # Add localhost to CSRF trusted origins for development
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost",
        "http://127.0.0.1",
    ]

INTERNAL_IPS = [
    "127.0.0.1",
]

# Production Security Settings
# These are only applied when DEBUG=False
if not DEBUG:
    # HTTPS/SSL Configuration
    # For Docker bootstrap (before certs), set USE_HTTPS=False in .env.
    USE_HTTPS = _env_bool("USE_HTTPS", default=True)
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=USE_HTTPS)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HSTS (HTTP Strict Transport Security)
    if USE_HTTPS:
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

    # Secure Cookies
    SESSION_COOKIE_SECURE = USE_HTTPS
    CSRF_COOKIE_SECURE = USE_HTTPS
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    # Additional Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

    # Session age
    SESSION_COOKIE_AGE = 1209600  # 2 weeks

# Error Reporting via Email
ADMINS = [
    ("Admin", os.environ.get("ADMINS", "admin@fikrly.uz")),
]
MANAGERS = ADMINS
# NOTE: Email settings are configured below in the "Email backend & defaults" section


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # Performance monitoring (conditionally loaded)
    "django_extensions",
    # Model translation for multilingual DB fields
    "modeltranslation",
    # 'debug_toolbar',
    "frontend.apps.FrontendConfig",
]

# Only enable Silk in development or when explicitly enabled
SILK_ENABLED = os.environ.get("SILK_ENABLED", str(DEBUG)).lower() in ("true", "1", "t")
if SILK_ENABLED:
    INSTALLED_APPS.insert(INSTALLED_APPS.index("django_extensions"), "silk")

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "frontend.middleware.UzbekDefaultLocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "frontend.middleware.ContentSecurityPolicyMiddleware",
    "frontend.middleware.NoCacheMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "frontend.middleware.PostLoginRedirectMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Add Silk middleware only if enabled
if SILK_ENABLED:
    MIDDLEWARE.insert(1, "silk.middleware.SilkyMiddleware")

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "frontend" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.google_analytics",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

# Caching (Redis)
REDIS_URL = os.environ.get("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# ... existing code ...

DB_ENGINE = os.environ.get("DB_ENGINE", "django.db.backends.postgresql")
DB_NAME = os.environ.get("DB_NAME", "fikrly_db")
DB_USER = os.environ.get("DB_USER", "fikrly_user")
DB_PASSWORD = os.environ.get("DB_PASSWORD", "fikrly_uz")
DB_HOST = os.environ.get("DB_HOST", "db")  # docker compose service name default
DB_PORT = os.environ.get("DB_PORT", "5432")

if DB_ENGINE.endswith("sqlite3") or DB_ENGINE.endswith("sqlite"):
    if not DEBUG:
        raise ImproperlyConfigured(
            "SQLite is disabled when DEBUG=False. Configure PostgreSQL via DB_ENGINE/DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT."
        )
    # SQLite expects a file path for NAME
    if DB_NAME and DB_NAME.endswith(".sqlite3"):
        sqlite_path = Path(DB_NAME)
        if not sqlite_path.is_absolute():
            sqlite_path = BASE_DIR / DB_NAME
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": str(sqlite_path),
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": str(BASE_DIR / "db.sqlite3"),
            }
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": (
                int(DB_PORT)
                if DB_PORT is not None and str(DB_PORT).isdigit()
                else DB_PORT
            ),
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
            "CONN_HEALTH_CHECKS": True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "uz"

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ("uz", _("O'zbek")),
    ("ru", _("Русский")),
]

# Default language used by django-modeltranslation when creating translated fields
MODELTRANSLATION_DEFAULT_LANGUAGE = "uz"

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True
USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "static",
    BASE_DIR / "public",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Trust the X-Forwarded-Proto header even in debug mode (for Cloudflare Tunnel)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# Authentication / django-allauth
SITE_ID = int(os.environ.get("SITE_ID", "2"))

# Skip the intermediate "Continue" page for social login
SOCIALACCOUNT_LOGIN_ON_GET = True
# Auto-connect social account to an existing account with the same email
# (Google verifies email ownership, so this is safe)
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
            "prompt": "select_account",
        },
        "OAUTH_PKCE_ENABLED": True,
    }
}

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Ensure links are generated with HTTPS
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# Email login configuration (email verification still disabled)
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_UNIQUE_EMAIL = True  # required when using email as a login method
# Prefer new-format settings; classic ones removed to avoid deprecation
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_SIGNUP_REDIRECT_URL = "/"
ACCOUNT_ADAPTER = "frontend.adapters.AccountAdapter"
SOCIALACCOUNT_ADAPTER = "frontend.adapters.SocialAccountAdapter"
ACCOUNT_FORMS = {
    "signup": "frontend.allauth_forms.CustomSignupForm",
}

# Stricter allauth rate limits (env-overridable)
ACCOUNT_RATE_LIMITS = {
    "login": os.environ.get("ACCOUNT_RATE_LIMIT_LOGIN", "15/5m"),
    "login_failed": os.environ.get("ACCOUNT_RATE_LIMIT_LOGIN_FAILED", "5/15m"),
    "signup": os.environ.get("ACCOUNT_RATE_LIMIT_SIGNUP", "5/1h"),
    "reset_password": os.environ.get("ACCOUNT_RATE_LIMIT_RESET_PASSWORD", "5/1h"),
    "reset_password_from_key": os.environ.get(
        "ACCOUNT_RATE_LIMIT_RESET_PASSWORD_FROM_KEY", "10/1h"
    ),
    "change_password": os.environ.get("ACCOUNT_RATE_LIMIT_CHANGE_PASSWORD", "5/1h"),
    "confirm_email": os.environ.get("ACCOUNT_RATE_LIMIT_CONFIRM_EMAIL", "3/1h"),
    "manage_email": os.environ.get("ACCOUNT_RATE_LIMIT_MANAGE_EMAIL", "10/1h"),
}

# Email backend & defaults
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "fikrlyuzb@gmail.com")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = os.environ.get("EMAIL_SUBJECT_PREFIX", "[Fikrly] ")

# Allow override in DEBUG via env
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")
if not EMAIL_BACKEND:
    EMAIL_BACKEND = (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    )

# If SMTP backend, read SMTP settings from env
if EMAIL_BACKEND.endswith("smtp.EmailBackend"):
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in (
        "1",
        "true",
        "yes",
    )
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

# Telegram notifications (optional)
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
# Secret token sent by Telegram in X-Telegram-Bot-Api-Secret-Token header.
# Must be [A-Za-z0-9_-] — we derive one from the bot token if not set explicitly.
_tg_secret_default = ""
if TELEGRAM_BOT_TOKEN:
    import hashlib as _hashlib
    _tg_secret_default = _hashlib.sha256(TELEGRAM_BOT_TOKEN.encode()).hexdigest()
TELEGRAM_WEBHOOK_SECRET = os.environ.get("TELEGRAM_WEBHOOK_SECRET", _tg_secret_default)
# Site base URL used in notification links and webhook registration
SITE_URL = os.environ.get("SITE_URL", "https://fikrly.uz")
# Comma-separated chat IDs (can be user IDs or group IDs)
TELEGRAM_ADMIN_CHAT_IDS = [
    cid.strip()
    for cid in os.environ.get("TELEGRAM_ADMIN_CHAT_IDS", "").split(",")
    if cid.strip()
]
TELEGRAM_REVIEWS_CHAT_IDS = [
    cid.strip()
    for cid in os.environ.get("TELEGRAM_REVIEWS_CHAT_IDS", "").split(",")
    if cid.strip()
]
TELEGRAM_ERROR_CHAT_IDS = [
    cid.strip()
    for cid in os.environ.get("TELEGRAM_ERROR_CHAT_IDS", "").split(",")
    if cid.strip()
]
TELEGRAM_ERRORS_ENABLED = os.environ.get("TELEGRAM_ERRORS_ENABLED", "false").lower() in (
    "1",
    "true",
    "yes",
)

# Google Analytics
GA_MEASUREMENT_ID = os.environ.get("GA_MEASUREMENT_ID", "")


# ============================================
# PERFORMANCE MONITORING (Django Silk)
# ============================================
SILKY_PYTHON_PROFILER = True
SILKY_PYTHON_PROFILER_BINARY = True
SILKY_META = True
SILKY_INTERCEPT_PERCENT = 100  # Profile 100% of requests in dev
SILKY_MAX_RECORDED_REQUESTS = 10000
SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 10

# Only enable Silk in development
if not DEBUG:
    SILKY_INTERCEPT_PERCENT = 0  # Disable in production


# ============================================
# LOGGING CONFIGURATION
# ============================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "structured": {
            "format": '{{"level":"{levelname}","time":"{asctime}","logger":"{name}","module":"{module}","message":"{message}"}}',
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "errors.log",
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 5,
            "formatter": "structured",
            "filters": ["require_debug_false"],
        },
        "telegram_errors": {
            "level": "ERROR",
            "class": "frontend.logging_handlers.TelegramErrorHandler",
            "formatter": "verbose",
            "filters": ["require_debug_false"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["error_file", "telegram_errors", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        "frontend": {
            "handlers": ["console", "file", "telegram_errors"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if not TELEGRAM_ERRORS_ENABLED:
    LOGGING["handlers"].pop("telegram_errors", None)
    for logger_name in ("django.request", "frontend"):
        LOGGING["loggers"][logger_name]["handlers"] = [
            handler
            for handler in LOGGING["loggers"][logger_name]["handlers"]
            if handler != "telegram_errors"
        ]

# Create logs directory
import os

os.makedirs(BASE_DIR / "logs", exist_ok=True)


# ============================================
# RATE LIMITING
# ============================================
RATELIMIT_ENABLE = not DEBUG  # Disable in development
RATELIMIT_USE_CACHE = "default"
RATELIMIT_VIEW = "frontend.views.ratelimit_error"


# (Security headers are set at the top of settings.py in the Production Security Settings block)


# ============================================
# CONTENT SECURITY POLICY (CSP)
# ============================================
CSP_ENFORCE = not DEBUG and _env_bool("CSP_ENFORCE", default=True)
CSP_REPORT_ONLY = _env_bool("CSP_REPORT_ONLY", default=False)

CSP_POLICY = os.environ.get(
    "CSP_POLICY",
    " ".join(
        [
            "default-src 'self';",
            "base-uri 'self';",
            "object-src 'none';",
            "frame-ancestors 'none';",
            "form-action 'self';",
            "script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://www.googletagmanager.com;",
            "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;",
            "font-src 'self' data: https://fonts.gstatic.com;",
            "img-src 'self' data: blob: https:;",
            "connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com;",
            "frame-src 'self';",
            "upgrade-insecure-requests;",
        ]
    ),
)
