# Generated by Django 5.2.5 on 2025-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
