# Generated by Django 5.2.5 on 2025-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_reviewattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
