# Generated by Django 5.2.5 on 2025-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_company_image_company_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="library_image_path",
            field=models.CharField(
                blank=True,
                help_text="Masalan: company_library/mylogo.png",
                max_length=255,
            ),
        ),
    ]
