# Generated by Django 5.2.5 on 2025-09-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0008_company_library_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="approval_requested",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
