# Generated by Django 5.2.5 on 2025-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0011_reviewreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="owner_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="owner_response_text",
            field=models.TextField(blank=True),
        ),
    ]
