# Generated by Django 5.2.4 on 2025-09-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0013_phoneotp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewAttachment",
        ),
    ]
