# Generated by Django 5.2.4 on 2025-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_companylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon_svg', models.TextField(blank=True, help_text="SVG path elementi, masalan: <path d='M12 2L2 7L12 12L22 7L12 2Z'/>", verbose_name='SVG icon kodi')),
                ('color', models.CharField(choices=[('red', 'Qizil'), ('orange', "To'q sariq"), ('yellow', 'Sariq'), ('green', 'Yashil'), ('blue', "Ko'k"), ('purple', 'Binafsha'), ('pink', 'Pushti'), ('gray', 'Kulrang')], default='gray', max_length=20, verbose_name='Rang')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Kichik raqam birinchi ko'rsatiladi", verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
