# Generated by Django 5.2.4 on 2025-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Agar o'chirilsa, saytda ko'rinmaydi"),
        ),
    ]
