# Generated by Django 5.2.4 on 2025-11-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0020_review_like_count_reviewlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="verified_purchase",
            field=models.BooleanField(default=False),
        ),
    ]
