# Generated by Django 5.2.4 on 2025-11-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0021_alter_review_verified_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Kompaniya logotipi (kvadrat shaklda tavsiya etiladi)",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
