# Generated by Django 5.2.4 on 2025-11-28 18:01

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0022_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Kompaniya logotipi (kvadrat shaklda tavsiya etiladi)",
                null=True,
                upload_to=frontend.models.company_logo_path,
            ),
        ),
    ]
