# Generated by Django 5.2.4 on 2025-12-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0023_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description_ru",
            field=models.TextField(blank=True, verbose_name="Tavsif (Rus tilida)"),
        ),
    ]
