# Generated by Django 5.2.4 on 2025-12-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_businesscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='frontend.businesscategory'),
        ),
    ]
