# Generated by Django 5.2.4 on 2025-12-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_businesscategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Bosh sahifada ko'rsatish"),
        ),
    ]
