# Generated by Django 5.2.4 on 2025-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_businesscategory_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
