# Generated by Django 5.2.4 on 2025-12-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0029_company_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="Logo uchun tashqi URL (agar fayl yuklanmasa)"
            ),
        ),
    ]
