# Generated by Django 5.2.4 on 2025-12-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0030_company_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo_scale",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Logo masshtabi foizda (masalan: 100 = asl o'lcham, 150 = 1.5x kattalashtirish)",
            ),
        ),
    ]
