# Generated by Django 5.2.4 on 2025-12-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0031_company_logo_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="receipt",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="review_receipts/",
                verbose_name="Xarid cheki",
            ),
        ),
    ]
