# Generated by Django 5.2.4 on 2025-12-07 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0032_review_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("company_edit", "Company Edited"),
                    ("approval_requested", "Review Approval Requested"),
                    ("review_approved", "Review Approved"),
                    ("owner_responded", "Owner Responded"),
                    ("review_created", "Review Created"),
                    ("review_reported", "Review Reported"),
                    ("company_claim_requested", "Company Claim Requested"),
                    ("company_claim_verified", "Company Claim Verified"),
                    ("contact_revealed", "Contact Revealed"),
                    ("company_liked", "Company Liked"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_active", "-rating"], name="frontend_co_is_acti_6b5463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_active", "-review_count"],
                name="frontend_co_is_acti_13b361_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["company", "is_approved", "-created_at"],
                name="frontend_re_company_99e814_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "is_approved", "-created_at"],
                name="frontend_re_user_id_59287d_idx",
            ),
        ),
    ]
