# Generated by Django 5.2.4 on 2026-01-21 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0034_rename_avtomobilsozlik_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewHelpfulVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="not_helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["company", "is_approved", "-helpful_count"],
                name="frontend_re_company_4f44fc_idx",
            ),
        ),
        migrations.AddField(
            model_name="reviewhelpfulvote",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpful_votes",
                to="frontend.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewhelpfulvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_helpful_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reviewhelpfulvote",
            index=models.Index(
                fields=["review", "user"], name="frontend_re_review__6f63df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewhelpfulvote",
            unique_together={("review", "user")},
        ),
    ]
