# Generated by Django 5.2.4 on 2026-01-21 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0036_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("first_review", "First Review"),
                            ("helpful_10", "10 Helpful Votes"),
                            ("helpful_50", "50 Helpful Votes"),
                            ("helpful_100", "100 Helpful Votes"),
                            ("reviews_10", "10 Reviews"),
                            ("reviews_50", "50 Reviews"),
                            ("reviews_100", "100 Reviews"),
                            ("streak_7", "7 Day Streak"),
                            ("streak_30", "30 Day Streak"),
                            ("level_5", "Level 5"),
                            ("level_10", "Level 10"),
                            ("level_25", "Level 25"),
                            ("verified", "Verified Reviewer"),
                            ("expert", "Category Expert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🏆", max_length=10)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_new",
                    models.BooleanField(
                        default=True, help_text="Show as new notification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Review image (will be compressed automatically)",
                        upload_to="review_images/",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Review Image",
                "verbose_name_plural": "Review Images",
                "ordering": ["order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("secret_key", models.CharField(blank=True, max_length=32)),
                (
                    "backup_codes",
                    models.JSONField(default=list, help_text="List of backup codes"),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Two-Factor Authentication",
                "verbose_name_plural": "Two-Factor Authentications",
            },
        ),
        migrations.CreateModel(
            name="UserGamification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1)),
                ("xp", models.PositiveIntegerField(default=0)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("helpful_votes_received", models.PositiveIntegerField(default=0)),
                ("companies_reviewed", models.PositiveIntegerField(default=0)),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Consecutive days with activity"
                    ),
                ),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Gamification",
                "verbose_name_plural": "User Gamifications",
            },
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="frontend_co_view_co_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="frontend_co_cat_act_rat_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="frontend_re_company_liked_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="frontend_re_user_created_idx",
        ),
        migrations.AddField(
            model_name="badge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="frontend.review",
            ),
        ),
        migrations.AddField(
            model_name="twofactorauth",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="two_factor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergamification",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="badge",
            unique_together={("user", "badge_type")},
        ),
    ]
