# Generated by Django 5.2.4 on 2026-01-21 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0037_badge_reviewimage_twofactorauth_usergamification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="verification_document",
            field=models.FileField(
                blank=True,
                help_text="Tasdiqlash hujjati (litsenziya, guvohnoma)",
                null=True,
                upload_to="verification_docs/",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Admin izoh (tasdiqlash sababi)"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_requested_at",
            field=models.DateTimeField(
                blank=True, help_text="Tasdiqlash so'ralgan sana", null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Tasdiqlangan biznes (admin tomonidan tekshirilgan)",
            ),
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("reviews_pdf", "Reviews PDF"),
                            ("reviews_excel", "Reviews Excel"),
                            ("user_data", "User Data (GDPR)"),
                            ("business_data", "Business Data"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/")),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Export filters (company_id, date_range, etc.)",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="File auto-deletes after this date (7 days)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Export",
                "verbose_name_plural": "Data Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("fake", "Fake Review"),
                            ("inappropriate", "Inappropriate Content"),
                            ("offensive", "Offensive Language"),
                            ("duplicate", "Duplicate Review"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="What action was taken (deleted, approved, warned)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flagged_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="frontend.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Flag",
                "verbose_name_plural": "Review Flags",
                "ordering": ["-created_at"],
            },
        ),
    ]
