# Generated by Django 5.2.4 on 2026-02-19 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_company_logo_url_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='businesscategory',
                    name='name_ru',
                    field=models.CharField(max_length=100, null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='businesscategory',
                    name='name_uz',
                    field=models.CharField(max_length=100, null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='company',
                    name='name_ru',
                    field=models.CharField(max_length=255, null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='company',
                    name='name_uz',
                    field=models.CharField(max_length=255, null=True, unique=True),
                ),
                migrations.AddIndex(
                    model_name='company',
                    index=models.Index(fields=['category_fk', 'is_active', '-rating'], name='frontend_co_categor_3e94da_idx'),
                ),
                migrations.AddIndex(
                    model_name='company',
                    index=models.Index(fields=['city', 'is_active'], name='frontend_co_city_5356d4_idx'),
                ),
                migrations.AddIndex(
                    model_name='company',
                    index=models.Index(fields=['is_verified', 'is_active'], name='frontend_co_is_veri_34e16c_idx'),
                ),
            ],
        ),
    ]
