# Generated by Django 5.2.4 on 2026-02-24 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0044_businesscategory_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesscategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Biznes Kategoriya",
                "verbose_name_plural": "Biznes Kategoriyalar (Filtrlarda ishlatiladi)",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar (Admin tomonidan boshqariladi)",
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "company"),
                name="unique_review_per_user_per_company",
            ),
        ),
    ]
