# Generated by Django 5.2.4 on 2026-02-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0048_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
    ]
