# Generated by Django 5.2.4 on 2026-02-25 14:42

import django.db.models.deletion
import frontend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0049_remove_company_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_claimed',
            field=models.BooleanField(default=False, help_text='Biznes egasi tomonidan egallangan va tasdiqlangan'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Tasdiqlangan biznes egasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessOwnershipClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('position', models.CharField(choices=[('owner', 'Egasi (Owner)'), ('manager', 'Menejer (Manager)'), ('other', 'Boshqa (Other)')], default='owner', max_length=20, verbose_name='Lavozim')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to=frontend.models.claim_proof_upload_path, verbose_name='Tasdiq hujjati')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=20, verbose_name='Holat')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.CharField(blank=True, max_length=50)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_claims', to='frontend.company', verbose_name='Kompaniya')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ownership_claims', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqdi")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_claims', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Biznes egallash so'rovi",
                'verbose_name_plural': "Biznes egallash so'rovlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='frontend_bu_company_8ee13d_idx'), models.Index(fields=['status', '-created_at'], name='frontend_bu_status_dbdd54_idx')],
            },
        ),
    ]
