# Generated by Django 5.2.4 on 2026-03-11

from django.db import migrations, models
from django.utils.text import slugify


def fill_company_slugs(apps, schema_editor):
    Company = apps.get_model("frontend", "Company")
    db_alias = schema_editor.connection.alias
    seen = set()
    for company in Company.objects.using(db_alias).order_by("id"):
        base = slugify(company.name, allow_unicode=False)
        if not base:
            base = slugify(company.name, allow_unicode=True)
        if not base:
            base = f"company-{company.pk}"
        slug = base
        n = 2
        while slug in seen or Company.objects.using(db_alias).filter(slug=slug).exclude(pk=company.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        seen.add(slug)
        company.slug = slug
        company.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0050_company_is_claimed_company_owner_and_more"),
    ]

    operations = [
        # Step 1: add nullable so existing rows don't violate the unique constraint
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                max_length=280,
                help_text="SEO-friendly URL segment, avto-yaratiladi",
            ),
        ),
        # Step 2: backfill a unique slug for every existing company
        migrations.RunPython(fill_company_slugs, migrations.RunPython.noop),
        # Step 3: now that all rows have a value, make NOT NULL (matches model)
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                blank=True,
                unique=True,
                max_length=280,
                help_text="SEO-friendly URL segment, avto-yaratiladi",
            ),
        ),
    ]
